spring:
  data:
    mongodb:
      authentication-database: admin
#      username: root
#      password: password
      database: snorlax
      port: 27017
      host: localhost
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/snorlax?useTimezone=true&serverTimezone=America/Sao_Paulo
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: 'true'
    validationQuery: SELECT 1
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    show-sql: 'true'

logging:
  level:
    io:
      micrometer: DEBUG

server:
  http2:
    enabled: true

graphql:
  playground:
    mapping: /playground
    endpoint: /graphql
    subscriptionEndpoint: /subscriptions
    enabled: true
    pageTitle: Playground

